# yaml-language-server: $schema=https://moonrepo.dev/schemas/tasks.json
$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  docker/build:
    command:
      - docker
      - build
      - -f
      - $projectSource/Dockerfile
      - -t
      - langeretechnikgmbh/$projectName:latest
      - .
    options:
      runFromWorkspaceRoot: true
      runInCI: false
      cache: false
